apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-demo
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: "paulovitorcl/argocd-rollout-demo"
    notifications.argoproj.io/subscribe.on-health-degraded.github: "paulovitorcl/argocd-rollout-demo"
    notifications.argoproj.io/subscribe.on-sync-running.github: "paulovitorcl/argocd-rollout-demo"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paulovitorcl/argocd-rollout-demo.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true